config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: { registrations: 'registrations' }

  root 'orders#new'

  resource :order do
    member do
      get :all
      patch :add_product
      patch :remove_product
      post :reset
      post :save
      post :add_note
    end
  end

  resource :setting do
    member do
      get :index
      patch :update, as: :update_current
    end
  end
end

app/models/setting.rb
# frozen_string_literal: true

class Setting < ApplicationRecord
  def self.current
    Setting.first
  end

  def self.valid?
    current.nil?
  end

  def self.printers
    CupsPrinter.get_all_printer_names
  end

  def self.cups_food_printer
    CupsPrinter.new current.food_printer
  end

  def self.cups_drink_printer
    CupsPrinter.new current.drink_printer
  end

  def self.cups_customer_printer
    CupsPrinter.new current.customer_printer
  end

  def self.using_esc?
    current.using_esc
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_settings

  def index
    @printers = Setting.printers
  end

  def update
    if @settings.update(setting_params)
      redirect_to settings_path, notice: 'Salvato correttamente'
    else
      render :index
    end
  end

  private

  def current_settings
    @settings = if Setting.valid?
                  Setting.new
                else
                  Setting.current
                end
  end

  # Only allow a trusted parameter "white list" through.
  def setting_params
    params.require(:setting)
          .permit(:food_printer, :drink_printer, :customer_printer, :using_esc)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.haml
.display-4.m-2
  Settings

.btn.btn-link= link_to 'Pagina iniziale', root_path

.row.justify-content-center
  .col-11.col-md-8.card
    = form_with model: @settings, url: update_current_setting_path, local: true, method: :patch, class: 'card-body m-2' do |f|
      .form-group
        = f.label :food_printer
        = f.select :food_printer, @printers, class: 'form-control'
      .form-group
        = f.label :drink_printer
        = f.select :drink_printer, @printers, class: 'form-control'
      .form-group
        = f.label :customer_printer
        = f.select :customer_printer, @printers, class: 'form-control'
      .form-group
        = f.label :using_esc
        = f.check_box :using_esc
      
      .form-group
        = f.submit "Salva", class: 'btn btn-primary'