config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :settings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
             controllers: { registrations: 'registrations' }

  root 'orders#new'

  resource :order do
    member do
      get :all
      patch :add_product
      patch :remove_product
      post :reset
      post :save
      post :add_note
    end
  end

  resource :setting do
    member do
      get :index
      patch :update, as: :update_current
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  default_scope { order(created_at: :desc) }

  def products_with_quantity
    list = []

    order_items.each do |item|
      qty = item.quantity
      product = item.product
      product.order_quantity = qty

      list.append product
    end

    list
  end

  def quantity_of(product)
    order_items.where(product_id: product&.id).first.quantity
  rescue StandardError
    0
  end

  def foods_with_quantity
    products_with_quantity.map { |item| item if item.food? }.compact
  end

  def drinks_with_quantity
    products_with_quantity.map { |item| item if item.drink? }.compact
  end

  def drinks
    products.map { |p| p if p.drink? }
            .compact
  end

  def foods
    products.map { |p| p if p.food? }
            .compact
  end

  def add_product(product)
    return unless product&.is_a? Product

    order_item = order_items.where(product_id: product.id).first
    if order_item
      order_item.quantity += 1
      order_item.save!
    else
      products << product
    end

    self.total += product.price
    save!
  end

  def remove_product(product)
    return unless product.is_a? Product

    order_item = order_items.where(product_id: product.id).first

    return unless order_item

    if order_item.quantity > 1
      order_item.quantity -= 1
      order_item.save!
    else
      order_item.destroy!
    end
    self.total -= product.price
    save!
  end

  def print_all
    print_food
    print_drink
    print_customer
  end

  def print_food
    return if food_receipt.nil? || food_receipt.empty?

    food_printer = Setting.cups_food_printer
    food_pdf = generate_pdf food_receipt

    print_pdf_a5 food_printer, food_pdf
  end

  def print_drink
    return if drink_receipt.nil? || drink_receipt.empty?

    drink_printer = Setting.cups_drink_printer
    drink_pdf = generate_pdf drink_receipt

    print_pdf_a5 drink_printer, drink_pdf
  end

  def print_customer
    customer_printer = Setting.cups_customer_printer

    if Setting.using_esc?
      customer_esc = Base64.decode64 customer_receipt_esc
      # TODO: Find a way to print with the pos printer
    else
      customer_pdf = generate_pdf customer_receipt
      print_pdf_a5 customer_printer, customer_pdf
    end
  end

  private

  def generate_pdf(content)
    WickedPdf.new.pdf_from_string(content)
  end

  def print_pdf_a5(printer, content)
    printer.print_data content, 'application/pdf', 'PageSize': 'A5'
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :current_settings_valid
  before_action :current_order
  before_action :relevant_sold_products

  def new
    @foods = Product.where category: 'food'
    @drinks = Product.where category: 'drink'
  end

  def all; end

  # Add product or increment quantity
  def add_product
    @product = Product.find(permitted_params[:id])
    @current_order.add_product @product

    @product.order_quantity = @current_order.quantity_of @product

    respond_to do |format|
      format.js
    end
  end

  def remove_product
    @product = Product.find(permitted_params[:id])
    @current_order.remove_product @product

    @product.order_quantity = @current_order.quantity_of @product

    respond_to do |format|
      format.js
    end
  end

  def add_note
    note = params[:order][:note]
    error = t('errors.blank') if note.empty?

    respond_to do |format|
      format.js do
        if error
          render js: "error = document.getElementById('modalError');
          if(error != null){
          error.innerHTML = '#{t('errors.blank')}';
          }"
        else
          @current_order.update note: note.html_safe
          flash[:success] = t('orders.note.saved')
          redirect_to :root
        end
      end
    end
  end

  def save
    if @current_order.products&.size&.positive?
      generate_receipts
      print
      @current_order.completed = true
      @current_order.save!

      flash[:success] = t('orders.saved')
    else
      flash[:danger] = t('orders.empty')
    end

    redirect_to :root
  end

  def print(order = @current_order)
    order.print_all
  end

  private

  def permitted_params
    params.permit(:id)
  end

  def current_order
    user_id = current_user.id
    orders_not_completed = Order.where(user_id: user_id, completed: false)

    @current_order = if orders_not_completed.empty?
                       Order.create user_id: user_id, completed: false
                     else
                       orders_not_completed.first
                     end
  end

  def generate_receipts(order = @current_order)
    unless (foods = order.foods_with_quantity).empty?
      order.food_receipt = render_to_string partial: 'staff_receipt',
                                            locals: { order_id: order.id,
                                                      product_type: t('foods.name'),
                                                      items: foods }
    end

    unless (drinks = order.drinks_with_quantity).empty?
      order.drink_receipt = render_to_string partial: 'staff_receipt',
                                             locals: { order_id: order.id,
                                                       product_type: t('drinks.name'),
                                                       items: drinks }
    end

    order.customer_receipt_esc = render_to_string partial: 'customer_receipt_esc',
                                                  locals: { pos_view: Escpos::Printer.new,
                                                            order_id: order.id,
                                                            items: order.products_with_quantity }

    order.customer_receipt = render_to_string partial: 'customer_receipt',
                                              locals: { order_id: order.id,
                                                        items: order.products_with_quantity }
    order.save!
  end

  def relevant_sold_products
    @relevant_products = [
      { name: t('products.cocks_sold'),
        quantity: OrderItem.cocks_sold },
      { name: t('products.sausages_sold'),
        quantity: OrderItem.sausages_sold }
    ]
  end

  def current_settings_valid
    redirect_to :settings, notice: 'Seleziona le stampanti da utilizzare e salva' if Setting.valid?
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/_customer_receipt.html.haml
:css
  body {
    /* A5 dimensions */
    width: 148.5mm;
    margin: 0;
    padding: 20px;
  }

  mb {
    margin-bottom: 20px;
  }

  mb-2 {
    margin-bottom: 30px;
  }

  mrow {
    margin-bottom: 5px;
  }

  bold {
    font-
  }

%h1.mb= order_id
%hr.mb
%h2.mb-2= t('products.name')
%table
  %tr
    %th
      QTY
    %th
    - items.each do |item|
      %tr
        %td
          %h3= item.order_quantity
        %td
          %h3= item.name

app/views/orders/_customer_receipt_esc.haml
- pos_view << Escpos::Helpers.center
- pos_view << Escpos::Helpers.quad_text(order_id)

- pos_view << Escpos::Helpers.left
- items.each do |item|
  - pos_view << Escpos::Helpers.text("#{item.order_quantity}x   #{item.name}")

= pos_view.to_base64

app/views/orders/_modal_note.html.haml
%button.btn.btn-info{ 'data-toggle': 'modal', 'data-target': '#modalNote' }
  = t('orders.note.show')

.modal.fade#modalNote{ 'tabIndex': '-1', 'role': 'dialog', 'aria-hidden': 'true' }
  .modal-dialog.modal-dialog-centered{ 'role': 'document' }
    .modal-content
      .modal-header
        %h5.modal-title#modalNote= t('orders.note.add')
        %button.close{ 'data-dismiss': 'modal' }
          %span{ 'aria-hidden': 'true' }
            &times;
      .modal-body
        #modalError.m-3.text-danger
        = form_with model: order, url: add_note_order_path(id: order.id), method: :post do |f|
          = f.text_area :note, class: 'form-control mb-3', rows: 3
          = f.submit t('common.save'), class: 'btn btn-primary btn-block'
          

app/views/orders/_product_item.html.haml
%li.list-group-item.d-flex.justify-content-between.align-items-center{ id: "item-#{product.id}" }
  %span.badge.badge-primary.badge-pill
    %h5.m-0{id: "item-quantity-#{product.id}"}= product.order_quantity
  .font-weight-bold= product.name
  = form_with model: product, url: remove_product_order_path(id: product.id) do |orderForm|
    = orderForm.submit t('products.remove'), class: 'btn btn-danger'

app/views/orders/_products_list.html.haml
= form_with model: item, url: url, class: 'col-6 col-md-4 col-lg-3 m-2' do |f|
  - color = if item.color then item.color else 'primary' end
  = f.submit "#{item.id}. #{item.name}", class: "btn btn-#{color} btn-link text-wrap text-white font-weight-bold p-4", style: 'font-size: 1.5em; height: 100%; width: 100%'

app/views/orders/_staff_receipt.html.haml
:css
  body {
    /* A5 dimensions */
    width: 148.5mm;
    margin: 0;
    padding: 20px;
  }

  mb {
    margin-bottom: 20px;
  }

  mb-2 {
    margin-bottom: 30px;
  }

  mrow {
    margin-bottom: 5px;
  }

  bold {
    font-
  }

%h1.mb= order_id
%hr.mb
%h2.mb-2= product_type
%table
  %tr
    %th
      QTY
    %th= t('products.name')
    - items.each do |item|
      %tr
        %td
          %h3= item.order_quantity
        %td
          %h3= item.name

app/views/orders/add_product.js.haml
var item = document.getElementById("item-quantity-#{@product.id}");

if (item === null) {
var list = document.getElementById("listProducts");
list.innerHTML = list.innerHTML + "#{escape_javascript(render('product_item', product: @product))}";
} else {
item.innerHTML = "#{@product.order_quantity}";
}

document.getElementById("totalOrder").innerHTML = "#{@current_order.total}";

app/views/orders/new.html.haml
.row
  .col-12.col-md-8#accordion
    .card
      .card-header#headFoods
        %h5.mb-0
          %button.btn.btn-link.btn-block{ 'data-toggle': 'collapse', 'data-target': '#contentFoods', 'aria-expanded': 'true', 'aria-controls': 'contentFoods' }
            %h4= t('foods.name')

      .collapse.show#contentFoods{ 'aria-labelledby': 'headFoods', 'data-parent': '#accordion' }
        .card-body
          .row.justify-content-center.scrollable-accordion
            - @foods.each do |food|
              = render partial: 'products_list', locals: { item: food, url: add_product_order_path(id: food.id) }
    .card
      .card-header#headDrinks
        %h5.mb-0
          %button.btn.btn-link.btn-block{ 'data-toggle': 'collapse', 'data-target': '#contentDrinks', 'aria-expanded': 'true', 'aria-controls': 'contentDrinks' }
            %h4
              = t('drinks.name')

      .collapse#contentDrinks{ 'aria-labelledby': 'headDrinks', 'data-parent': '#accordion' }
        .card-body
          .row.justify-content-center.scrollable-accordion
            - @drinks.each do |drink|
              = render partial: 'products_list', locals: { item: drink, url: add_product_order_path(id: drink.id) }
  .card.col-12.col-md-4
    .card-body
      .card-title
        %h2.font-weight-bold
          = @current_order.id
          = render partial: 'modal_note', locals: { order: @current_order }
        .float-right= link_to t('settings.name'), settings_path
            
      %h5.card-subtitle=t('orders.id')
      %hr.m-3
      .card-group
        - @relevant_products&.each do |product|
          .card
            .card-body
              .card-title= product[:name]
              .font-weight-bold= product[:quantity]
      %hr
      .card.my-5
        .card-header
          %h4.card-title
            = t('products.list')
        .card-body
          %ul.list-group#listProducts.scrollable-revise-items
            - @current_order&.products_with_quantity.each do |product|
              = render 'product_item', product: product
      %hr.my-5
      .row
        %h1.col-12.col-md-6
          = t('orders.total') ++ " €"
          %span.font-weight-bold#totalOrder= @current_order.total
        = form_with model: @current_order, url: save_order_path, class: "col-12 col-md-6", method: :post, local: true do |orderForm|
          = orderForm.submit t('orders.save'), class: 'btn btn-lg btn-primary btn-block'

app/views/orders/remove_product.js.haml
if ( "#{@product.order_quantity}" === "0") {
var item = document.getElementById("item-#{@product.id}");
item.parentNode.removeChild(item);
} else {
var quantityItem = document.getElementById("item-quantity-#{@product.id}");
quantityItem.innerHTML = "#{@product.order_quantity}";
}

document.getElementById("totalOrder").innerHTML = "#{@current_order.total}";